# Site settings
title: Hello I am Twarit Waikar
description: My portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Twarit Waikar
user_description: I am a game developer specialising in engine programming and gameplay systems in C++ with interest in game designing, VR development, information security, and listening to lo-fi music.
user_title: Game & Software Developer
email: wtwarit@gmail.com
twitter_username: TwaritW
github_username:  IronicallySerious
gplus_username:  Twarit-Waikar

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
